"use client";

import { useState, useRef, useEffect } from "react";
import { toast } from "react-hot-toast";
import confetti from "canvas-confetti";
import { motion, AnimatePresence } from "framer-motion";

interface AiAutofillProps {
  classes: { id: string; name: string }[];
  initialCountries?: { id: string; country: string; country_flag: string | null }[];
  setValue: (field: any, value: any, options?: any) => void;
  isUserRequest?: boolean;
  onSuccess?: () => void;
}

export default function AnimalAiAutofill({
  classes,
  initialCountries,
  setValue,
  isUserRequest = false,
  onSuccess,
}: AiAutofillProps) {
  const [isDragOver, setIsDragOver] = useState(false);
  const [pastedText, setPastedText] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [showStats, setShowStats] = useState<{
    success: boolean;
    fieldsFilled: number;
    unresolvedClass?: string;
    resolvedClass?: string;
    matchedCountries: string[];
    unmatchedCountries: string[];
  } | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const [allCountries, setAllCountries] = useState<{ id: string; country: string; country_flag: string | null }[]>([]);

  useEffect(() => {
    if (!isUserRequest) {
      fetch("/api/countries?all=true")
        .then((res) => res.json())
        .then((data) => setAllCountries(data.data || []))
        .catch((err) => console.error("Failed to load countries for autofill:", err));
    }
  }, [isUserRequest]);

  const handleDownloadTemplate = () => {
    let templateContent = "";
    let fileName = "";

    if (isUserRequest) {
      templateContent = `Instructions:
1. Copy this entire prompt template.
2. Paste it into an AI chat (Gemini, ChatGPT, or Claude).
3. Replace the placeholder [INSERT ANIMAL NAME HERE] with the name of the animal you want to research.
4. Run the prompt.
5. Copy the JSON output generated by the AI.
6. Return to the ZooSite form and paste the JSON output or drag & drop the generated text file.

--- PROMPT START ---
You are an expert zoologist and research assistant.
Research the animal: "[INSERT ANIMAL NAME HERE]"

Provide the taxonomical, biological, conservation, and ecological details for this animal in the raw JSON format specified below.
Ensure all descriptions are written in high-quality, professional, engaging prose suitable for an educational zoo catalog.
Provide ONLY the JSON block. Do not include any introductory or concluding text.

JSON Format:
{
  "name": "Common English name of the animal, capitalized (e.g. Red Panda)",
  "scientific_name": "Scientific name in italics style text (e.g. Ailurus fulgens)",
  "family": "Taxonomic family (e.g. Ailuridae)",
  "genus": "Taxonomic genus (e.g. Ailurus)",
  "class": "Taxonomic class (e.g. Mammalia, Aves, Reptilia, Amphibia, Actinopterygii)",
  "description": "A rich 3-4 sentence educational summary about the animal's characteristics, behaviors, and ecological role.",
  "description_source": "Provide a reliable URL where information can be verified, e.g. a Wikipedia page or national geographic page.",
  "diet": "Primary diet. MUST be exactly one of: 'Herbivore', 'Carnivore', 'Omnivore' (e.g. Carnivore)",
  "lifespan_years": "Average lifespan range in years (e.g. 8 - 15 years)",
  "weight_kg": "Typical weight range (e.g. 3 - 6 kg)",
  "height_cm": "Typical height or length range (e.g. 50 - 64 cm)",
  "avg_speed_kmh": "Average movement speed range (e.g. 10 - 15 km/h)",
  "top_speed_kmh": "Maximum recorded top speed (e.g. 38 km/h)",
  "social_structure": "Social dynamics (e.g. Solitary, Packs, Harem)",
  "conservation_status": "Standard conservation status (e.g. Endangered, Vulnerable, Least Concern)",
  "synonyms": "Any common alternative names, synonyms, or historical names separated by commas (e.g. Firefox, Lesser Panda)"
}
--- PROMPT END ---`;
      fileName = "zoosite-user-ai-template.txt";
    } else {
      templateContent = `Instructions:
1. Copy this entire prompt template.
2. Paste it into an AI chat (Gemini, ChatGPT, or Claude).
3. Replace the placeholder [INSERT ANIMAL NAME HERE] with the name of the animal you want to research.
4. Run the prompt.
5. Copy the JSON output generated by the AI.
6. Return to the ZooSite form and paste the JSON output or drag & drop the generated text file.

--- PROMPT START ---
You are an expert zoologist and research assistant.
Research the animal: "[INSERT ANIMAL NAME HERE]"

Provide the taxonomical, biological, conservation, and ecological details for this animal in the raw JSON format specified below.
Ensure all descriptions are written in high-quality, professional, engaging prose suitable for an educational zoo catalog.
Provide ONLY the JSON block. Do not include any introductory or concluding text.

JSON Format:
{
  "name": "Common English name of the animal, capitalized (e.g. Red Panda)",
  "scientific_name": "Scientific name in italics style text (e.g. Ailurus fulgens)",
  "family": "Taxonomic family (e.g. Ailuridae)",
  "genus": "Taxonomic genus (e.g. Ailurus)",
  "ordo": "Diet Type. MUST be exactly one of: 'Herbivore', 'Carnivore', 'Omnivore' (e.g. Carnivore)",
  "class": "Taxonomic class (e.g. Mammalia, Aves, Reptilia, Amphibia, Actinopterygii)",
  "description": "A rich 3-4 sentence educational summary about the animal's characteristics, behaviors, and ecological role.",
  "description_source": "Provide a reliable URL where information can be verified, e.g. a Wikipedia page or national geographic page.",
  "diet": "Primary diet. MUST be exactly one of: 'Herbivore', 'Carnivore', 'Omnivore' (e.g. Carnivore)",
  "lifespan_years": "Average lifespan range in years (e.g. 8 - 15 years)",
  "weight_kg": "Typical weight range (e.g. 3 - 6 kg)",
  "height_cm": "Typical height or length range (e.g. 50 - 64 cm)",
  "avg_speed_kmh": "Average movement speed range (e.g. 10 - 15 km/h)",
  "top_speed_kmh": "Maximum recorded top speed (e.g. 38 km/h)",
  "social_structure": "Social dynamics (e.g. Solitary, Packs, Harem)",
  "conservation_status": "Standard conservation status (e.g. Endangered, Vulnerable, Least Concern)",
  "predators": "Common natural predators of this animal (e.g. Snow leopards, Martens)",
  "tags": ["Array of 3-5 tags representing the animal's diet, habitat type, and type (e.g. ['Mammal', 'Bamboo', 'Mountain'])"],
  "habitats": ["Array of primary habitats (e.g. ['Temperate Forests', 'Bamboo Forests'])"],
  "countries": ["Array of countries where the animal is natively found (e.g. ['Nepal', 'India', 'Bhutan', 'China'])"],
  "synonyms": "Any common alternative names, synonyms, or historical names separated by commas (e.g. Firefox, Lesser Panda)"
}
--- PROMPT END ---`;
      fileName = "zoosite-admin-ai-template.txt";
    }

    const blob = new Blob([templateContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success("AI Prompt Template downloaded!");
  };

  const processAiJson = (text: string) => {
    setIsProcessing(true);
    setShowStats(null);

    try {
      // 1. Attempt to extract JSON from string (handling potential markdown ```json blocks)
      let cleanText = text.trim();
      const markdownJsonRegex = /```(?:json)?\s*([\s\S]*?)\s*```/;
      const match = cleanText.match(markdownJsonRegex);
      if (match && match[1]) {
        cleanText = match[1].trim();
      }

      const json = JSON.parse(cleanText);

      // 2. Resolve field mappings
      let fieldsFilledCount = 0;
      const setFormVal = (field: any, val: any) => {
        if (val !== undefined && val !== null && val !== "") {
          setValue(field, val, { shouldDirty: true, shouldValidate: true });
          fieldsFilledCount++;
        }
      };

      // Base fields based on form mode (User request vs Admin)
      if (isUserRequest) {
        setFormVal("animal_name", json.name);
      } else {
        setFormVal("name", json.name);
      }

      // Normalize diet/ordo to standard dropdown values ("Herbivore", "Carnivore", "Omnivore")
      let parsedDiet = json.diet || "";
      let parsedOrdo = json.ordo || "";

      const normalizeDietString = (str: string) => {
        const lower = str.toLowerCase();
        if (lower.includes("carnivor")) return "Carnivore";
        if (lower.includes("herbivor")) return "Herbivore";
        if (lower.includes("omnivor")) return "Omnivore";
        return str;
      };

      parsedDiet = normalizeDietString(parsedDiet);
      parsedOrdo = normalizeDietString(parsedOrdo);

      if (!parsedDiet && parsedOrdo) {
        const normalized = normalizeDietString(parsedOrdo);
        if (["Carnivore", "Herbivore", "Omnivore"].includes(normalized)) {
          parsedDiet = normalized;
        }
      }
      if (!parsedOrdo && parsedDiet) {
        const normalized = normalizeDietString(parsedDiet);
        if (["Carnivore", "Herbivore", "Omnivore"].includes(normalized)) {
          parsedOrdo = normalized;
        }
      }

      setFormVal("scientific_name", json.scientific_name);
      setFormVal("family", json.family);
      setFormVal("genus", json.genus);
      setFormVal("ordo", parsedOrdo);
      setFormVal("description", json.description);
      setFormVal("description_source", json.description_source);
      setFormVal("diet", parsedDiet);
      setFormVal("lifespan_years", json.lifespan_years);
      setFormVal("weight_kg", json.weight_kg);
      setFormVal("height_cm", json.height_cm);
      setFormVal("avg_speed_kmh", json.avg_speed_kmh);
      setFormVal("top_speed_kmh", json.top_speed_kmh);
      setFormVal("social_structure", json.social_structure);
      setFormVal("conservation_status", json.conservation_status);
      setFormVal("predators", json.predators);
      setFormVal("synonyms", json.synonyms);

      // Resolve dropdown class_id
      let unresolvedClass: string | undefined = undefined;
      let resolvedClass: string | undefined = undefined;
      if (json.class) {
        const inputClass = json.class.toLowerCase().trim();
        const matchedClass = classes.find((c) => {
          const clsName = c.name.toLowerCase();
          return (
            clsName.includes(inputClass) ||
            inputClass.includes(clsName) ||
            (inputClass === "mammal" && clsName === "mammalia") ||
            (inputClass === "mammalia" && clsName.includes("mammal")) ||
            (inputClass.includes("bird") && clsName === "aves") ||
            (inputClass === "aves" && clsName.includes("bird")) ||
            (inputClass.includes("reptil") && clsName.includes("reptil")) ||
            (inputClass.includes("amphib") && clsName.includes("amphib")) ||
            (inputClass.includes("fish") && clsName.includes("actinopterygii"))
          );
        });

        if (matchedClass) {
          setValue("class_id", matchedClass.id, { shouldDirty: true, shouldValidate: true });
          resolvedClass = matchedClass.name;
          fieldsFilledCount++;
        } else {
          unresolvedClass = json.class;
        }
      }

      // Resolve Admin Only tags, habitats, and countries
      const matchedCountries: string[] = [];
      const unmatchedCountries: string[] = [];
      if (!isUserRequest) {
        if (Array.isArray(json.tags)) {
          setFormVal("tags", json.tags);
        }
        if (Array.isArray(json.habitats)) {
          setFormVal("habitats", json.habitats);
        }

        // Resolve countries using loaded allCountries list or initialCountries fallback
        const countryList = allCountries.length > 0 ? allCountries : initialCountries;
        if (Array.isArray(json.countries) && countryList) {
          const matchedCountryIds: string[] = [];
          json.countries.forEach((countryName: string) => {
            const trimmedName = countryName.toLowerCase().trim();
            const matched = countryList.find(
              (c) =>
                c.country.toLowerCase().trim() === trimmedName ||
                c.country.toLowerCase().trim().includes(trimmedName) ||
                trimmedName.includes(c.country.toLowerCase().trim())
            );

            if (matched) {
              matchedCountryIds.push(matched.id);
              matchedCountries.push(matched.country);
            } else {
              unmatchedCountries.push(countryName);
            }
          });

          if (matchedCountryIds.length > 0) {
            setValue("countries", matchedCountryIds, { shouldDirty: true, shouldValidate: true });
            fieldsFilledCount += matchedCountryIds.length;
          }
        }
      }

      // Show celebration confetti and toast
      confetti({
        particleCount: 80,
        spread: 60,
        origin: { y: 0.8 },
      });

      toast.success(`Form successfully auto-filled with ${fieldsFilledCount} attributes!`);
      
      setShowStats({
        success: true,
        fieldsFilled: fieldsFilledCount,
        unresolvedClass,
        resolvedClass,
        matchedCountries,
        unmatchedCountries,
      });

      if (onSuccess) {
        onSuccess();
      }
    } catch (err) {
      console.error(err);
      toast.error("Invalid AI JSON format. Please ensure you copied the complete JSON block.");
      setShowStats({
        success: false,
        fieldsFilled: 0,
        matchedCountries: [],
        unmatchedCountries: [],
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const handlePasteChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const text = e.target.value;
    setPastedText(text);
    if (text.trim().startsWith("{") || text.trim().startsWith("```")) {
      processAiJson(text);
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = () => {
    setIsDragOver(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        const text = event.target?.result as string;
        setPastedText(text);
        processAiJson(text);
      };
      reader.readAsText(file);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        const text = event.target?.result as string;
        setPastedText(text);
        processAiJson(text);
      };
      reader.readAsText(file);
    }
  };

  return (
    <div className="w-full bg-[#fafaf5] border border-[#c2c9bb] rounded-2xl p-6 shadow-sm font-['Manrope'] mb-8 overflow-hidden">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 border-b border-[#e3e3de] pb-4">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-full bg-[#2d5a27]/10 flex items-center justify-center shrink-0">
            <span className="material-symbols-outlined text-[#2d5a27] text-[28px] animate-pulse">
              robot_2
            </span>
          </div>
          <div>
            <h3 className="text-base font-bold text-[#1a1c19] font-['Plus_Jakarta_Sans'] flex items-center gap-1.5 uppercase tracking-wider">
              AI Auto-Fill Assistant
              <span className="px-2 py-0.5 text-[9px] bg-[#2d5a27]/10 text-[#2d5a27] rounded-full font-bold font-sans tracking-normal lowercase">
                beta
              </span>
            </h3>
            <p className="text-xs text-[#72796e]">
              Instant animal data population using your favorite AI model.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={handleDownloadTemplate}
          className="inline-flex items-center justify-center gap-2 px-4 py-2 text-xs font-bold text-white bg-[#2d5a27] hover:bg-[#1f3f1b] rounded-xl transition-all font-['Plus_Jakarta_Sans'] uppercase tracking-wider shadow-sm shrink-0 cursor-pointer"
        >
          <span className="material-symbols-outlined text-[16px]">download</span>
          Download AI Template
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Left Drag/Paste Area */}
        <div className="lg:col-span-3 flex flex-col gap-3">
          <label className="block text-xs font-bold text-[#1a1c19]/60 uppercase tracking-wider">
            Paste AI JSON Output or Drop File
          </label>
          <div
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            className={`relative flex flex-col items-center justify-center border-2 border-dashed rounded-xl p-4 transition-all min-h-[140px] cursor-pointer ${
              isDragOver
                ? "border-[#2d5a27] bg-[#2d5a27]/5"
                : showStats?.success
                ? "border-emerald-500 bg-emerald-50/10"
                : "border-[#1a1c19]/15 hover:border-[#2d5a27]/50 hover:bg-[#2d5a27]/2"
            }`}
            onClick={() => fileInputRef.current?.click()}
          >
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileChange}
              accept=".json,.txt"
              className="hidden"
            />
            {isProcessing ? (
              <div className="flex flex-col items-center gap-2">
                <span className="material-symbols-outlined animate-spin text-[32px] text-[#2d5a27]">
                  progress_activity
                </span>
                <span className="text-xs font-bold text-[#2d5a27]">Analyzing JSON Data...</span>
              </div>
            ) : showStats?.success ? (
              <div className="flex flex-col items-center text-center gap-1.5 p-2">
                <span className="material-symbols-outlined text-[36px] text-emerald-500">
                  check_circle
                </span>
                <span className="text-xs font-bold text-emerald-950 font-['Plus_Jakarta_Sans'] uppercase tracking-wider">
                  Success! Auto-Fill Complete
                </span>
                <span className="text-[11px] text-emerald-800/80">
                  Drag a new file or click here to overwrite existing fields.
                </span>
              </div>
            ) : (
              <div className="flex flex-col items-center text-center gap-1.5 p-2 pointer-events-none">
                <span className="material-symbols-outlined text-[32px] text-[#72796e]">
                  cloud_upload
                </span>
                <span className="text-xs font-bold text-[#1a1c19]/70 font-['Plus_Jakarta_Sans'] uppercase tracking-wider">
                  Drag & Drop prompt file or Click to Browse
                </span>
                <span className="text-[11px] text-[#72796e]">
                  Or paste the raw JSON block directly below.
                </span>
              </div>
            )}
          </div>

          <textarea
            value={pastedText}
            onChange={handlePasteChange}
            placeholder='{ "name": "Red Panda", ... }'
            className="w-full px-4 py-3 rounded-xl border border-[#1a1c19]/10 focus:border-[#2d5a27] outline-none text-xs bg-white font-mono min-h-[90px] shadow-inner resize-y transition-all"
          />
        </div>

        {/* Right Instructions / Report Panel */}
        <div className="lg:col-span-2 bg-[#f4f4ef] border border-[#e3e3de] rounded-xl p-4 flex flex-col justify-between text-xs text-[#72796e] leading-relaxed">
          <AnimatePresence mode="wait">
            {showStats ? (
              <motion.div
                key="stats"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="space-y-4"
              >
                <div className="flex items-center gap-2 border-b border-[#e3e3de] pb-2">
                  <span className="material-symbols-outlined text-[16px] text-[#2d5a27]">
                    analytics
                  </span>
                  <span className="font-bold text-[#1a1c19] uppercase tracking-wider font-['Plus_Jakarta_Sans'] text-[10px]">
                    Auto-Fill Report
                  </span>
                </div>

                <div className="space-y-2 font-['Manrope']">
                  <div className="flex justify-between items-center bg-white/60 p-2 rounded-lg border border-[#e3e3de]">
                    <span className="font-semibold text-[#1a1c19]/70">Attributes Set:</span>
                    <span className="font-bold text-[#2d5a27]">{showStats.fieldsFilled}</span>
                  </div>

                  {showStats.resolvedClass && (
                    <div className="flex justify-between items-center bg-emerald-50/40 p-2 rounded-lg border border-emerald-100">
                      <span className="font-semibold text-emerald-950">Resolved Class:</span>
                      <span className="font-bold text-emerald-800 uppercase tracking-wider text-[10px]">
                        {showStats.resolvedClass}
                      </span>
                    </div>
                  )}

                  {showStats.unresolvedClass && (
                    <div className="bg-amber-50/50 p-2 rounded-lg border border-amber-200 flex flex-col gap-1">
                      <div className="flex items-center gap-1 text-amber-900 font-bold">
                        <span className="material-symbols-outlined text-[14px]">warning</span>
                        Class Match Failed
                      </div>
                      <p className="text-[10px] text-amber-800/80 leading-normal">
                        AI output class "{showStats.unresolvedClass}" couldn't be matched automatically. Please select it manually.
                      </p>
                    </div>
                  )}

                  {!isUserRequest && showStats.matchedCountries.length > 0 && (
                    <div className="bg-white/60 p-2 rounded-lg border border-[#e3e3de] space-y-1">
                      <span className="font-semibold text-[#1a1c19]/70 block">
                        Matched Countries ({showStats.matchedCountries.length}):
                      </span>
                      <p className="text-[10px] text-[#2d5a27] font-semibold leading-normal">
                        {showStats.matchedCountries.join(", ")}
                      </p>
                    </div>
                  )}

                  {!isUserRequest && showStats.unmatchedCountries.length > 0 && (
                    <div className="bg-amber-50/50 p-2 rounded-lg border border-amber-200 space-y-1">
                      <span className="font-bold text-amber-900 block">
                        Unmatched Countries ({showStats.unmatchedCountries.length}):
                      </span>
                      <p className="text-[10px] text-amber-800/80 leading-normal">
                        {showStats.unmatchedCountries.join(", ")}
                      </p>
                    </div>
                  )}
                </div>
              </motion.div>
            ) : (
              <motion.div
                key="instructions"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="space-y-3"
              >
                <div className="flex items-center gap-2 border-b border-[#e3e3de] pb-2">
                  <span className="material-symbols-outlined text-[16px] text-[#2d5a27]">info</span>
                  <span className="font-bold text-[#1a1c19] uppercase tracking-wider font-['Plus_Jakarta_Sans'] text-[10px]">
                    How to use AI Auto-Fill
                  </span>
                </div>
                <ol className="list-decimal list-inside space-y-2 leading-relaxed text-[#72796e] pl-1 font-['Manrope']">
                  <li>
                    Click <strong className="text-[#2d5a27]">Download AI Template</strong> above to get the prompt file.
                  </li>
                  <li>
                    Paste the template text into an AI assistant like **Gemini** or **ChatGPT**.
                  </li>
                  <li>
                    Supply the target animal name and instruct it to generate the structured data.
                  </li>
                  <li>
                    Copy the JSON output from the AI and drop or paste it in the assistant block.
                  </li>
                </ol>
              </motion.div>
            )}
          </AnimatePresence>

          <div className="mt-4 pt-3 border-t border-[#e3e3de] flex items-center gap-1.5 justify-center text-[10px] text-[#72796e]/70 font-semibold font-['Plus_Jakarta_Sans'] uppercase tracking-wider">
            <span className="material-symbols-outlined text-[12px] text-emerald-500">lock</span>
            Processed 100% Client-Side
          </div>
        </div>
      </div>
    </div>
  );
}
