export const USER_PROMPT_TEMPLATE = `Instructions:
1. Copy this entire prompt template.
2. Paste it into an AI chat (Gemini, ChatGPT, or Claude).
3. Replace the placeholder [INSERT ANIMAL NAME HERE] with the name of the animal you want to research.
4. Run the prompt.
5. Copy the JSON output generated by the AI.
6. Return to the ZooSite form and paste the JSON output or drag & drop the generated text file.

--- PROMPT START ---
You are an expert zoologist and research assistant.
Research the animal: "[INSERT ANIMAL NAME HERE]"

Provide the taxonomical, biological, conservation, and ecological details for this animal in the raw JSON format specified below.
Ensure all descriptions are written in high-quality, professional, engaging prose suitable for an educational zoo catalog.
Provide ONLY the JSON block. Do not include any introductory or concluding text.

JSON Format:
{
  "name": "Common English name of the animal, capitalized (e.g. Red Panda)",
  "scientific_name": "Scientific name in italics style text (e.g. Ailurus fulgens)",
  "family": "Taxonomic family (e.g. Ailuridae)",
  "genus": "Taxonomic genus (e.g. Ailurus)",
  "class": "Taxonomic class (e.g. Mammalia, Aves, Reptilia, Amphibia, Actinopterygii)",
  "description": "A rich 3-4 sentence educational summary about the animal's characteristics, behaviors, and ecological role.",
  "description_source": "Provide a reliable URL where information can be verified, e.g. a Wikipedia page or national geographic page.",
  "diet": "Primary diet. MUST be exactly one of: 'Herbivore', 'Carnivore', 'Omnivore' (e.g. Carnivore)",
  "lifespan_years": "Average lifespan range in years (e.g. 8 - 15 years)",
  "weight_kg": "Typical weight range (e.g. 3 - 6 kg)",
  "height_cm": "Typical height or length range (e.g. 50 - 64 cm)",
  "avg_speed_kmh": "Average movement speed range (e.g. 10 - 15 km/h)",
  "top_speed_kmh": "Maximum recorded top speed (e.g. 38 km/h)",
  "social_structure": "Social dynamics (e.g. Solitary, Packs, Harem)",
  "conservation_status": "Standard conservation status (e.g. Endangered, Vulnerable, Least Concern)",
  "synonyms": "Any common alternative names, synonyms, or historical names separated by commas (e.g. Firefox, Lesser Panda)"
}
--- PROMPT END ---`;

export const ADMIN_PROMPT_TEMPLATE = `Instructions:
1. Copy this entire prompt template.
2. Paste it into an AI chat (Gemini, ChatGPT, or Claude).
3. Replace the placeholder [INSERT ANIMAL NAME HERE] with the name of the animal you want to research.
4. Run the prompt.
5. Copy the JSON output generated by the AI.
6. Return to the ZooSite form and paste the JSON output or drag & drop the generated text file.

--- PROMPT START ---
You are an expert zoologist and research assistant.
Research the animal: "[INSERT ANIMAL NAME HERE]"

Provide the taxonomical, biological, conservation, and ecological details for this animal in the raw JSON format specified below.
Ensure all descriptions are written in high-quality, professional, engaging prose suitable for an educational zoo catalog.
Provide ONLY the JSON block. Do not include any introductory or concluding text.

JSON Format:
{
  "name": "Common English name of the animal, capitalized (e.g. Red Panda)",
  "scientific_name": "Scientific name in italics style text (e.g. Ailurus fulgens)",
  "family": "Taxonomic family (e.g. Ailuridae)",
  "genus": "Taxonomic genus (e.g. Ailurus)",
  "ordo": "Diet Type. MUST be exactly one of: 'Herbivore', 'Carnivore', 'Omnivore' (e.g. Carnivore)",
  "class": "Taxonomic class (e.g. Mammalia, Aves, Reptilia, Amphibia, Actinopterygii)",
  "description": "A rich 3-4 sentence educational summary about the animal's characteristics, behaviors, and ecological role.",
  "description_source": "Provide a reliable URL where information can be verified, e.g. a Wikipedia page or national geographic page.",
  "diet": "Primary diet. MUST be exactly one of: 'Herbivore', 'Carnivore', 'Omnivore' (e.g. Carnivore)",
  "lifespan_years": "Average lifespan range in years (e.g. 8 - 15 years)",
  "weight_kg": "Typical weight range (e.g. 3 - 6 kg)",
  "height_cm": "Typical height or length range (e.g. 50 - 64 cm)",
  "avg_speed_kmh": "Average movement speed range (e.g. 10 - 15 km/h)",
  "top_speed_kmh": "Maximum recorded top speed (e.g. 38 km/h)",
  "social_structure": "Social dynamics (e.g. Solitary, Packs, Harem)",
  "conservation_status": "Standard conservation status (e.g. Endangered, Vulnerable, Least Concern)",
  "predators": "Common natural predators of this animal (e.g. Snow leopards, Martens)",
  "tags": ["Array of 3-5 tags representing the animal's diet, habitat type, and type (e.g. ['Mammal', 'Bamboo', 'Mountain'])"],
  "habitats": ["Array of primary habitats (e.g. ['Temperate Forests', 'Bamboo Forests'])"],
  "countries": ["Array of countries where the animal is natively found (e.g. ['Nepal', 'India', 'Bhutan', 'China'])"],
  "synonyms": "Any common alternative names, synonyms, or historical names separated by commas (e.g. Firefox, Lesser Panda)"
}
--- PROMPT END ---`;